import { z } from 'zod';
import { RESPONSE_MESSAGES } from '../constants/responseMessages.constant';
import { Gender } from '../constants/enums.constant';
import { NAME_REGEX, PASSWORD_REGEX } from '../constants/regex.constant';

export const signupSchema = z.object({
  first_name: z
    .string(RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .min(2, RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .max(50, RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .regex(NAME_REGEX, RESPONSE_MESSAGES.INVALID_CREDENTIALS),
  last_name: z
    .string(RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .min(2, RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .max(50, RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .regex(NAME_REGEX, RESPONSE_MESSAGES.INVALID_CREDENTIALS),
  email: z
    .email(RESPONSE_MESSAGES.INVALID_CREDENTIALS),
  password: z
    .string(RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .regex(PASSWORD_REGEX, RESPONSE_MESSAGES.INVALID_CREDENTIALS),
  gender: z
    .enum(Gender, RESPONSE_MESSAGES.INVALID_CREDENTIALS),
  age: z
    .number(RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .int(RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .gte(13, RESPONSE_MESSAGES.INVALID_CREDENTIALS)
    .lte(120, RESPONSE_MESSAGES.INVALID_CREDENTIALS)
});
